using System;
using Google.Protobuf.Reflection;

namespace EggLink.DanhengServer.Proto
{
	// Token: 0x02000512 RID: 1298
	public static class FeatureSwitchTypeReflection
	{
		// Token: 0x1700109E RID: 4254
		// (get) Token: 0x06003A35 RID: 14901 RVA: 0x000A00DF File Offset: 0x0009E2DF
		public static FileDescriptor Descriptor
		{
			get
			{
				return FeatureSwitchTypeReflection.descriptor;
			}
		}

		// Token: 0x0400172E RID: 5934
		private static FileDescriptor descriptor = FileDescriptor.FromGeneratedCode(Convert.FromBase64String(string.Concat(new string[]
		{
			"ChdGZWF0dXJlU3dpdGNoVHlwZS5wcm90byrHDgoRRmVhdHVyZVN3aXRjaFR5",
			"cGUSFwoTRkVBVFVSRV9TV0lUQ0hfTk9ORRAAEhcKE0ZFQVRVUkVfU1dJVENI",
			"X1NIT1AQARIeChpGRUFUVVJFX1NXSVRDSF9MSU5FVVBfTkFNRRACEiAKHEZF",
			"QVRVUkVfU1dJVENIX1JFQ0hBUkdFX1NIT1AQAxIbChdGRUFUVVJFX1NXSVRD",
			"SF9OSUNLTkFNRRAEEhwKGEZFQVRVUkVfU1dJVENIX1NJR05BVFVSRRAFEh0K",
			"GUZFQVRVUkVfU1dJVENIX0JBVFRMRVBBU1MQBhIcChhGRUFUVVJFX1NXSVRD",
			"SF9QVU5LX0xPUkQQBxIiCh5GRUFUVVJFX1NXSVRDSF9NT05USENBUkRfREFJ",
			"TFkQCBIgChxGRUFUVVJFX1NXSVRDSF9QSUNUVVJFX1NIQVJFEAkSGAoURkVB",
			"VFVSRV9TV0lUQ0hfUk9HVUUQChIcChhGRUFUVVJFX1NXSVRDSF9DSEFMTEVO",
			"R0UQCxIZChVGRUFUVVJFX1NXSVRDSF9DT0NPT04QDBIXChNGRUFUVVJFX1NX",
			"SVRDSF9SQUlEEA0SIwofRkVBVFVSRV9TV0lUQ0hfTUFaRV9QTEFORV9FVkVO",
			"VBAOEiEKHUZFQVRVUkVfU1dJVENIX0FDVElWSVRZX1BBTkVMEA8SGgoWRkVB",
			"VFVSRV9TV0lUQ0hfTUFJTEJPWBAQEhgKFEZFQVRVUkVfU1dJVENIX1FVRVNU",
			"EBESGAoURkVBVFVSRV9TV0lUQ0hfR0FDSEEQEhIXChNGRUFUVVJFX1NXSVRD",
			"SF9DSEFUEBMSJgoiRkVBVFVSRV9TV0lUQ0hfTU9ESUZZX0ZSSUVORF9BTElB",
			"UxAUEhsKF0ZFQVRVUkVfU1dJVENIX1VTRV9JVEVNEBUSJAogRkVBVFVSRV9T",
			"V0lUQ0hfQUNUSVZJVFlfU0NIRURVTEUQFhIfChtGRUFUVVJFX1NXSVRDSF9G",
			"QVJNX0VMRU1FTlQQFxIkCiBGRUFUVVJFX1NXSVRDSF9BQ0hJRVZFTUVOVF9M",
			"RVZFTBAYEiUKIUZFQVRVUkVfU1dJVENIX0RBSUxZX0FDVElWRV9MRVZFTBAZ",
			"EiAKHEZFQVRVUkVfU1dJVENIX1BMQVlFUl9SRVRVUk4QGhIlCiFGRUFUVVJF",
			"X1NXSVRDSF9GSVJTVF9TRVRfTklDS05BTUUQGxImCiJGRUFUVVJFX1NXSVRD",
			"SF9NQUlOX01JU1NJT05fUkVXQVJEEBwSJQohRkVBVFVSRV9TV0lUQ0hfU1VC",
			"X01JU1NJT05fUkVXQVJEEB0SHgoaRkVBVFVSRV9TV0lUQ0hfUEFNX01JU1NJ",
			"T04QHhIgChxGRUFUVVJFX1NXSVRDSF9EQUlMWV9NSVNTSU9OEB8SHwobRkVB",
			"VFVSRV9TV0lUQ0hfREVTVFJPWV9JVEVNECASJAogRkVBVFVSRV9TV0lUQ0hf",
			"Q09OU1VNRV9JVEVNX1RVUk4QIRIhCh1GRUFUVVJFX1NXSVRDSF9ST0dVRV9N",
			"T0RJRklFUhAiEh4KGkZFQVRVUkVfU1dJVENIX0NIRVNTX1JPR1VFECMSJAog",
			"RkVBVFVSRV9TV0lUQ0hfQ0hFU1NfUk9HVUVfQk9BUkQQJBIcChhGRUFUVVJF",
			"X1NXSVRDSF9ST0xMX1NIT1AQJRIcChhGRUFUVVJFX1NXSVRDSF9INV9SRVRV",
			"Uk4QJhIbChdGRUFUVVJFX1NXSVRDSF9PRkZFUklORxAnEiMKH0ZFQVRVUkVf",
			"U1dJVENIX1NFUlZFUl9SRURfUE9JTlQQKBIoCiRGRUFUVVJFX1NXSVRDSF9N",
			"T05PUE9MWV9PUFRJT05fUkFUSU8QKRItCilGRUFUVVJFX1NXSVRDSF9NT05P",
			"UE9MWV9HRVRfUkFGRkxFX1RJQ0tFVBAqEi4KKkZFQVRVUkVfU1dJVENIX01P",
			"Tk9QT0xZX1RBS0VfUkFGRkxFX1JFV0FSRBArEi0KKUZFQVRVUkVfU1dJVENI",
			"X0NIQUxMRU5HRV9SRUNPTU1FTkRfTElORVVQECwSKAokRkVBVFVSRV9TV0lU",
			"Q0hfUFNOX01FTUJFUl9TSElQX0NIRUNLEC0SKwonRkVBVFVSRV9TV0lUQ0hf",
			"UExBWUVSX0JPQVJEX0RFVkVMT1BNRU5UEC4SFgoSRkVBVFVSRV9TV0lUQ0hf",
			"UFZQEC8SHQoZRkVBVFVSRV9TV0lUQ0hfUk9HVUVfTU9ERRAwEiIKHkZFQVRV",
			"UkVfU1dJVENIX1JPR1VFX1RPVVJOX1VHQxAxEikKJUZFQVRVUkVfU1dJVENI",
			"X1JFTElDX0ZJTFRFUl9QTEFOX05BTUUQMhIqCiZGRUFUVVJFX1NXSVRDSF9N",
			"QVpFX0lURU1fVVNFX0JVRkZfRFJPUBAzEhoKFkZFQVRVUkVfU1dJVENIX1JF",
			"RF9ET1QQNBIlCiFGRUFUVVJFX1NXSVRDSF9HQU1FX1NUQVRFX1NFUlZJQ0UQ",
			"NUIeqgIbRWdnTGluay5EYW5oZW5nU2VydmVyLlByb3RvYgZwcm90bzM="
		})), new FileDescriptor[0], new GeneratedClrTypeInfo(new Type[]
		{
			typeof(FeatureSwitchType)
		}, null, null));
	}
}
